import { Router } from "express";
import addressRoutes from "./addressRoutes";
import academicRoutes from "./academicRoutes";
import attendanceRoutes from "./attendanceRoutes";
import authRoutes from "./authRoutes";
import dashboardRoutes from "./dashboardRoutes";
import examRoutes from "./examRoutes";
import feeRoutes from "./feeRoutes";
import noticeRoutes from "./noticeRoutes";
import schoolRoutes from "./schoolRoutes";
import settingsRoutes from "./settingsRoutes";
import studentRoutes from "./studentRoutes";
import teacherRoutes from "./teacherRoutes";
import uploadRoutes from "./uploadRoutes";
import exportRoutes from "./exportRoutes";
import timetableRoutes from "./timetableRoutes";
import homeworkRoutes from "./homeworkRoutes";
import parentRoutes from "./parentRoutes";
import notificationRoutes from "./notificationRoutes";
import libraryRoutes from "./libraryRoutes";
import laboratoryRoutes from "./laboratoryRoutes";
import transportRoutes from "./transportRoutes";
import hrRoutes from "./hrRoutes";
import accountingRoutes from "./accountingRoutes";
import studentPortalRoutes from "./studentPortalRoutes";
import teacherPortalRoutes from "./teacherPortalRoutes";

const router = Router();

router.use("/auth", authRoutes);
router.use("/schools", schoolRoutes);
router.use("/students", studentRoutes);
router.use("/teachers", teacherRoutes);
router.use("/academics", academicRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/exams", examRoutes);
router.use("/fees", feeRoutes);
router.use("/notices", noticeRoutes);
router.use("/settings", settingsRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/addresses", addressRoutes);
router.use("/uploads", uploadRoutes);
router.use("/exports", exportRoutes);
router.use("/timetable", timetableRoutes);
router.use("/homework", homeworkRoutes);
router.use("/parent", parentRoutes);
router.use("/notifications", notificationRoutes);
router.use("/library", libraryRoutes);
router.use("/laboratory", laboratoryRoutes);
router.use("/transport", transportRoutes);
router.use("/hr", hrRoutes);
router.use("/accounting", accountingRoutes);
router.use("/student", studentPortalRoutes);
router.use("/teacher", teacherPortalRoutes);

export default router;
