import { Router } from "express";
import addressRoutes from "./addressRoutes.js";
import academicRoutes from "./academicRoutes.js";
import academicPromotionRoutes from "./academicPromotionRoutes.js";
import academicManagementRoutes from "./academicManagementRoutes.js";
import academicCalendarRoutes from "./academicCalendarRoutes.js";
import subjectAssignmentRoutes from "./subjectAssignmentRoutes.js";
import attendanceRoutes from "./attendanceRoutes.js";
import dailyAttendanceRoutes from "./dailyAttendanceRoutes.js";
import fieldDutyRoutes from "./fieldDutyRoutes.js";
import authRoutes from "./authRoutes.js";
import dashboardRoutes from "./dashboardRoutes.js";
import examRoutes from "./examRoutes.js";
import feeRoutes from "./feeRoutes.js";
import noticeRoutes from "./noticeRoutes.js";
import bannerRoutes from "./bannerRoutes.js";
import schoolRoutes from "./schoolRoutes.js";
import settingsRoutes from "./settingsRoutes.js";
import studentRoutes from "./studentRoutes.js";
import teacherRoutes from "./teacherRoutes.js";
import collegeStaffRoutes from "./collegeStaffRoutes.js";
import uploadRoutes from "./uploadRoutes.js";
import exportRoutes from "./exportRoutes.js";
import timetableRoutes from "./timetableRoutes.js";
import homeworkRoutes from "./homeworkRoutes.js";
import parentRoutes from "./parentRoutes.js";
import notificationRoutes from "./notificationRoutes.js";
import libraryRoutes from "./libraryRoutes.js";
import laboratoryRoutes from "./laboratoryRoutes.js";
import transportRoutes from "./transportRoutes.js";
import hrRoutes from "./hrRoutes.js";
import accountingRoutes from "./accountingRoutes.js";
import adminRoutes from "./adminRoutes.js";
import collegeAdministratorRoutes from "./collegeAdministratorRoutes.js";
import complaintRoutes from "./complaintRoutes.js";
import studentPortalRoutes from "./studentPortalRoutes.js";
import teacherPortalRoutes from "./teacherPortalRoutes.js";
import userRoutes from "./userRoutes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/users", userRoutes);
router.use("/admins", adminRoutes);
router.use("/college-administrators", collegeAdministratorRoutes);
router.use("/schools", schoolRoutes);
router.use("/students", studentRoutes);
router.use("/teachers", teacherRoutes);
router.use("/college-staff", collegeStaffRoutes);
router.use("/academics", academicRoutes);
router.use("/academics/subject-assignments", subjectAssignmentRoutes);
router.use("/academic-promotion", academicPromotionRoutes);
router.use("/academic-management", academicManagementRoutes);
router.use("/academic-calendar", academicCalendarRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/daily-attendance", dailyAttendanceRoutes);
router.use("/field-duty", fieldDutyRoutes);
router.use("/exams", examRoutes);
router.use("/fees", feeRoutes);
router.use("/notices", noticeRoutes);
router.use("/complaints", complaintRoutes);
router.use("/banners", bannerRoutes);
router.use("/settings", settingsRoutes);
router.use("/dashboard", dashboardRoutes);
router.use("/addresses", addressRoutes);
router.use("/uploads", uploadRoutes);
router.use("/exports", exportRoutes);
router.use("/timetable", timetableRoutes);
router.use("/homework", homeworkRoutes);
router.use("/parent", parentRoutes);
router.use("/notifications", notificationRoutes);
router.use("/library", libraryRoutes);
router.use("/laboratory", laboratoryRoutes);
router.use("/transport", transportRoutes);
router.use("/hr", hrRoutes);
router.use("/accounting", accountingRoutes);
router.use("/student", studentPortalRoutes);
router.use("/teacher", teacherPortalRoutes);

export default router;
