import { jsx as _jsx, jsxs as _jsxs, Fragment as _Fragment } from "react/jsx-runtime";
import { MessageSquare, Paperclip, Pin } from "lucide-react";
import { Badge } from "components/ui/badge";
import { cn } from "lib/utils";
import { formatPostDate, getDisplayStatus, TYPE_BADGE_COLORS, TYPE_COLORS, TYPE_LABELS } from "./homeworkUtils";
export const ClassroomPostCard = ({ post, onOpen }) => {
    const status = getDisplayStatus(post);
    const attachmentCount = post.attachments.length + (post.links?.length ?? 0);
    return (_jsxs("button", { type: "button", onClick: () => onOpen(post), className: cn("w-full min-w-0 rounded-2xl border border-slate-200 border-l-4 bg-white p-4 text-left shadow-sm transition hover:shadow-md", TYPE_COLORS[post.type]), children: [_jsx("div", { className: "flex flex-wrap items-start justify-between gap-2", children: _jsxs("div", { className: "min-w-0 flex-1 space-y-1", children: [_jsxs("div", { className: "flex flex-wrap items-center gap-2", children: [post.isPinned ? (_jsxs("span", { className: "inline-flex items-center gap-1 text-xs font-medium text-slate-600", children: [_jsx(Pin, { className: "h-3.5 w-3.5" }), "Pinned"] })) : null, _jsx(Badge, { className: TYPE_BADGE_COLORS[post.type], children: TYPE_LABELS[post.type] }), status ? _jsx(Badge, { className: status.className, children: status.label }) : null] }), _jsx("h3", { className: "text-base font-semibold text-slate-900", children: post.title }), _jsx("p", { className: "line-clamp-2 text-sm text-slate-600", children: post.description })] }) }), _jsxs("div", { className: "mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-slate-500", children: [_jsx("span", { className: "font-medium text-slate-700", children: post.teacherName }), _jsx("span", { children: "\u00B7" }), _jsx("span", { children: post.subjectName }), post.topic ? (_jsxs(_Fragment, { children: [_jsx("span", { children: "\u00B7" }), _jsx("span", { children: post.topic })] })) : null, _jsx("span", { children: "\u00B7" }), _jsx("span", { children: formatPostDate(post.createdAt) }), post.dueDateBs ? (_jsxs(_Fragment, { children: [_jsx("span", { children: "\u00B7" }), _jsxs("span", { children: ["Due ", post.dueDateBs] })] })) : null] }), _jsxs("div", { className: "mt-2 flex items-center gap-4 text-xs text-slate-500", children: [attachmentCount > 0 ? (_jsxs("span", { className: "inline-flex items-center gap-1", children: [_jsx(Paperclip, { className: "h-3.5 w-3.5" }), attachmentCount, " attachment", attachmentCount === 1 ? "" : "s"] })) : null, post.commentCount > 0 ? (_jsxs("span", { className: "inline-flex items-center gap-1", children: [_jsx(MessageSquare, { className: "h-3.5 w-3.5" }), post.commentCount, " comment", post.commentCount === 1 ? "" : "s"] })) : null] })] }));
};
