import type {
  LABORATORY_EQUIPMENT_CONDITIONS,
  LABORATORY_EQUIPMENT_STATUSES,
  LABORATORY_INVENTORY_STOCK_STATUSES,
  LABORATORY_ITEM_KINDS,
  LABORATORY_REPORT_TYPES,
  LABORATORY_STOCK_MOVEMENT_TYPES,
  LABORATORY_STOCK_PRIORITIES,
  LABORATORY_STOCK_REQUEST_STATUSES,
  LABORATORY_TYPES
} from "./laboratory-constants.js";

export type LaboratoryType = (typeof LABORATORY_TYPES)[number];
export type LaboratoryItemKind = (typeof LABORATORY_ITEM_KINDS)[number];
export type LaboratoryEquipmentCondition = (typeof LABORATORY_EQUIPMENT_CONDITIONS)[number];
export type LaboratoryEquipmentStatus = (typeof LABORATORY_EQUIPMENT_STATUSES)[number];
export type LaboratoryStockMovementType = (typeof LABORATORY_STOCK_MOVEMENT_TYPES)[number];
export type LaboratoryStockRequestStatus = (typeof LABORATORY_STOCK_REQUEST_STATUSES)[number];
export type LaboratoryStockPriority = (typeof LABORATORY_STOCK_PRIORITIES)[number];
export type LaboratoryInventoryStockStatus = (typeof LABORATORY_INVENTORY_STOCK_STATUSES)[number];
export type LaboratoryReportType = (typeof LABORATORY_REPORT_TYPES)[number];

export interface LaboratoryRecord {
  _id: string;
  schoolId: string;
  name: string;
  code?: string;
  type: LaboratoryType;
  customName?: string;
  department?: string;
  academicProgram?: string;
  description?: string;
  location?: string;
  roomNumber?: string;
  inChargeTeacherId?: string | null;
  inChargeTeacherName?: string;
  remarks?: string;
  isActive: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface LaboratoryCategoryRecord {
  _id: string;
  schoolId: string;
  laboratoryId: string;
  name: string;
  isDefault: boolean;
  createdAt?: string;
  updatedAt?: string;
}

export interface LaboratoryEquipmentRecord {
  _id: string;
  schoolId: string;
  laboratoryId: string;
  categoryId: string;
  categoryName?: string;
  laboratoryName?: string;
  name: string;
  itemCode: string;
  itemKind: LaboratoryItemKind;
  brand?: string;
  equipmentModel?: string;
  unit?: string;
  quantity: number;
  availableQuantity: number;
  issuedQuantity: number;
  minimumStockLevel: number;
  requiredQuantity: number;
  purchaseDateBs?: string;
  supplier?: string;
  purchaseCost?: number;
  storageLocation?: string;
  condition: LaboratoryEquipmentCondition;
  equipmentStatus: LaboratoryEquipmentStatus;
  status: LaboratoryInventoryStockStatus;
  description?: string;
  remarks?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface LaboratoryIssueRecord {
  _id: string;
  schoolId: string;
  equipmentId: string;
  equipmentName?: string;
  laboratoryId?: string;
  laboratoryName?: string;
  teacherId: string;
  teacherName?: string;
  quantity: number;
  issuedDateBs: string;
  dueDateBs: string;
  returnedDateBs?: string;
  status: "ISSUED" | "RETURNED" | "OVERDUE";
  createdAt?: string;
  updatedAt?: string;
}

export interface LaboratoryStockMovementRecord {
  _id: string;
  schoolId: string;
  laboratoryId: string;
  laboratoryName?: string;
  equipmentId: string;
  equipmentName?: string;
  type: LaboratoryStockMovementType;
  quantity: number;
  previousStock: number;
  newStock: number;
  notes?: string;
  performedByUserId?: string;
  performedByName?: string;
  createdAt?: string;
  updatedAt?: string;
}

export interface LaboratoryStockRequestRecord {
  _id: string;
  schoolId: string;
  laboratoryId: string;
  laboratoryName?: string;
  equipmentId?: string | null;
  equipmentName: string;
  categoryName?: string;
  currentStock: number;
  minimumStock: number;
  requiredQuantity: number;
  priority: LaboratoryStockPriority;
  requestedByUserId?: string;
  requestedByName?: string;
  requestDateBs: string;
  status: LaboratoryStockRequestStatus;
  adminNotes?: string;
  autoGenerated: boolean;
  receivedQuantity?: number;
  createdAt?: string;
  updatedAt?: string;
}

export interface LaboratoryDashboardResponse {
  totalLaboratories: number;
  totalEquipment: number;
  availableEquipment: number;
  issuedEquipment: number;
  remainingStock: number;
  lowStockItemsCount: number;
  outOfStockItemsCount: number;
  damagedItemsCount: number;
  pendingRequestsCount: number;
  lowStockItems: LaboratoryEquipmentRecord[];
  recentlyAdded: LaboratoryEquipmentRecord[];
  recentlyUpdated: LaboratoryEquipmentRecord[];
  /** When true, metrics are scoped to the teacher's assigned laboratories only. */
  scopedToAssignedLabs: boolean;
}

export interface LaboratoryReportResponse {
  reportType: LaboratoryReportType;
  generatedAt: string;
  rows: Record<string, unknown>[];
  summary?: Record<string, number | string>;
}
